name: Glauber Ramos Website
description: Blog sobre Pensamentos e Insights de Glauber Ramos
url: http://glauberramos.com

pygments: true

# defaults
sass:
  syntax: scss
  style:  compressed  # nested|expanded|compact|compressed

permalink: :title.html
#baseurl: glauberramos.com