name: Glauber Ramos Website
email: contato@glauberramos.com
description: Portfolio Glauber Ramos
url: http://glauberramos.com
twitter_username: glauberamos
github_username: glauberramos

highlighter: true

sass:
  sass_dir: assets/stylesheets
  style: compressed

permalink: :title.html
#baseurl: glauberramos.com

gems:
  - jekyll-autoprefixer
